# version: '3.8'
# services:
#   wordpress:
#     image: wordpress-test
#     ports: 
#       - "9000"
#     depends_on:
#       - mysql
#     environment:
#       WORDPRESS_DB_HOST: mysql
#       WORDPRESS_DB_USER: root
#       WORDPRESS_DB_PASSWORD: "coffee"
#       WORDPRESS_DB_NAME: wordpress
#   mariadb:
#     image: "mariadb-test"
#     environment:
#       MYSQL_DATABASE: wordpress
#       MYSQL_ROOT_PASSWORD: "coffee"
#     volumes:
#       - ./mysql:/var/lib/mysql
# networks:
#   ohyeah:
#     ipam:
#       driver: default
services:
  nginx:
    image: nginx-test
    ports:
      - "443:443"