# version: '3.8'
# services:
#   wordpress:
#     image: wordpress-test
#     ports: 
#       - "9000"
#     depends_on:
#       - mysql
#     environment:
#       WORDPRESS_DB_HOST: mysql
#       WORDPRESS_DB_USER: root
#       WORDPRESS_DB_PASSWORD: "coffee"
#       WORDPRESS_DB_NAME: wordpress
#   mariadb:
#     image: "mariadb-test"
#     environment:
#       MYSQL_DATABASE: wordpress
#       MYSQL_ROOT_PASSWORD: "coffee"
#     volumes:
#       - ./mysql:/var/lib/mysql
# networks:
#   ohyeah:
#     ipam:
#       driver: default
services:
  wordpress:
    image: wordpress-test
    ports:
      - "443:443"
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "needcoffee"
      WORDPRESS_DB_NAME: wordpress
    networks:
      ohyeah:
        ipv4_address: "10.56.1.21"
  mariadb:
    image: mariadb-test
    ports:
      - "3306"
    environment:
      MARIADB_ROOT_PASSWORD: "needcoffee"
      MARIADB_DATABASE: mariadb
      MARIADB_USER: ldoppler
      MARIADB_PASSWORD: "needcoffeetoo"
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      ohyeah:
        ipv4_address: "10.56.1.20"
networks:
  ohyeah:
    ipam:
      driver: default
