services:
  wordpress:
    image: wordpress-test
    ports:
      - "9000"
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "needcoffee"
      WORDPRESS_DB_NAME: wordpress
    networks:
      - ohyeah
  mariadb:
    image: mariadb-test
    ports:
      - "3306"
    depends_on:
      - nginx
    environment:
      MARIADB_ROOT_PASSWORD: "needcoffee"
      MARIADB_DATABASE: mariadb
      MARIADB_USER: ldoppler
      MARIADB_PASSWORD: "needcoffeetoo"
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      - ohyeah
  nginx:
    image: nginx-test
    ports:
      - "443:443"
    networks:
      - ohyeah
networks:
  ohyeah:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16