services:
  wordpress:
    image: wordpress-test
    container_name: wordpress
    ports:
      - "9000:9000"  # Assuming the WordPress container listens on port 80
    depends_on:
      - mariadb
    # environment:
    #   WORDPRESS_DB_HOST: mariadb:3306
    #   WORDPRESS_DB_NAME: wordpress
    #   WORDPRESS_DB_USER: ldoppler
    #   WORDPRESS_DB_PASSWORD: "needcoffee"
    #   WORDPRESS_TABLE_PREFIX: wp_
    env_file:
      - .env
      
    volumes:
      - wordpress_data:/var/www/html
      - /run/php:/run/php
    networks:
      - ohyeah
    entrypoint: ["/bin/sh", "/usr/local/bin/wp-setup.sh"]

  mariadb:
    image: mariadb-test
    container_name: mariadb
    ports:
      - "3306:3306"
    # environment:
    #   MARIADB_ROOT_PASSWORD: "needcoffee"
    #   MARIADB_DATABASE: wordpress
    #   MARIADB_USER: ldoppler
    #   MARIADB_PASSWORD: "needcoffee"
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./requirements/mariadb/conf/init.sql:/docker-entrypoint-initdb.d/init.sql
      - /run/mysql:/run/mysql
    networks:
      - ohyeah

  nginx:
    image: nginx-test
    container_name: nginx
    ports:
      - "4430:4430"
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
      - /run/php:/run/php
    networks:
      - ohyeah

volumes:
  mariadb_data:
  wordpress_data:
networks:
  ohyeah:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
